### ISSUE TITLE
It should be @threadSafe

### ISSUE THREAD

**Issue by rotilho** [mojohaus/cobertura-maven-plugin#15]
The plugin should be @threadSafe.

15:01:50 [WARNING] *****************************************************************
15:01:50 [WARNING] \* Your build is requesting parallel execution, but project      *
15:01:50 [WARNING] \* contains the following plugin(s) that are not marked as       *
15:01:50 [WARNING] \* @threadSafe to support parallel building.                     *
15:01:50 [WARNING] \* While this /may/ work fine, please look for plugin updates    *
15:01:50 [WARNING] \* and/or request plugins be made thread-safe.                   *
15:01:50 [WARNING] \* If reporting an issue, report it against the plugin in        *
15:01:50 [WARNING] \* question, not against maven-core                              *
15:01:50 [WARNING] *****************************************************************
15:01:50 [WARNING] The following plugins are not marked @threadSafe in MODULE-NAME:
15:01:50 [WARNING] org.codehaus.mojo:cobertura-maven-plugin:2.7

**Comment by Macadoshis** [comment]
+1

**Comment by urbanq** [comment]
+1

**Comment by persapiens** [comment]
+1

**Comment by niklas-ekman-telia** [comment]
+1

**Comment by hasankhalil** [comment]
Hello, 
is it actually a thread-safe plugin?
